version: "2"
services:
  ui:
    build: ./client-app
    ports:
      - "80:3000"
    links:
      - api
    networks:
      - webappnetwork
  api:
    build: ./server-app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
